redis:
  image: redis

postgres:
  image: postgres
  environment:
    - POSTGRES_PASSWORD=sentry
    - POSTGRES_USER=sentry
  volumes:
    - /var/lib/postgresql/data

sentry:
  image: sentry
  links:
    - redis
    - postgres
  ports:
    - "8081:9000"
  environment:
    - SENTRY_SECRET_KEY=SENTRY_SECRET_KEY

sentry-worker:
  image: sentry
  links:
    - redis
    - postgres
  command: sentry run worker
  environment:
    - SENTRY_SECRET_KEY=SENTRY_SECRET_KEY
    
sentry-cron:
  image: sentry
  links:
    - redis
    - postgres
  command: sentry run cron
  environment:
    - SENTRY_SECRET_KEY=SENTRY_SECRET_KEY    
